# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Far Horizon Crop Insurance
description: >- # this means to ignore newlines until "baseurl:"
  Far Horizon Crop Insurance provides California growers the protection they need—to esnure the fruits of their labor and sustain California agriculture
baseurl: "" # the subpath of your site, e.g. /blog
url: "farhorizoninsurance.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

content:
  title: "We provide our growers the protection they need—to esnure the fruits of their labor and sustain California agriculture"
  background: "/app/images/far-horizon-background.jpg"


contact:
  title: "Let's get in touch."
  phone: "530-674-1340"

footer:
  email:
    title: "Sign up to receive updates!"
    form: ""
  address: "1130 Bridge St #A Yuba City, CA 95991"